services:
    application:
        container_name: fidu_application
        environment:
            PHP_IDE_CONFIG: "serverName=fidu.localhost"
        build:
            context: ./docker/php
            args:
                - APP_ENV=${APP_ENV}
                - UID=${UID}
                - INSTALL_XDEBUG=${INSTALL_XDEBUG}
        env_file:
            - .env
        expose:
            - "9000"
        links:
            - database
        volumes:
            - ./:/home/fidu/application:delegated
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        depends_on:
            - database
        extra_hosts:
            - host.docker.internal:host-gateway
        networks:
            - fidu_internal_network

    nginx:
        container_name: fidu_nginx
        build:
            context: ./docker/nginx
            args:
                - APP_ENV=${APP_ENV}
                - APPLICATION_CONTAINER=application
                - APPLICATION_PORT=9000
        links:
            - application
            - database
        ports:
            - "8000:80"
        volumes_from:
            - application
        volumes:
            - ./:/home/fidu/application
            - ./var/volumes/nginx/logs:/var/log/nginx:rw,delegated
        networks:
            - fidu_internal_network

    database:
        container_name: fidu_database
        image: postgres:16.4-alpine
        restart: always
        hostname: database
        ports:
            - '5434:5432'
        environment:
            POSTGRES_DB: "fidu"
            POSTGRES_USER: "fidu"
            POSTGRES_PASSWORD: "fidu"
        volumes:
            - ./var/volumes/postgres/data:/var/lib/postgresql/data
            - ./var/volumes/postgres/dumps:/dumps:rw,delegated
        networks:
            - fidu_internal_network

networks:
    fidu_internal_network:
        name: fidu_internal_network
